// This code was generated in whole or in part by GenAI tool

using MultiAgentWinFormsApp.Interfaces;

namespace MultiAgentWinFormsApp.Agents;

public class AddNoticeAgent : BaseAgent
{
    public override string Name => "Add Notice Agent";
    public AddNoticeAgent(ILLMService llmService) : base(llmService) { }
    public override string Prompt => base.Prompt + Environment.NewLine + $"Insert a comment notice that this code was generated by GenAI tool:";
}
